import {useMemo,useState} from 'react'; import {Cpu,Gauge,Search,ShieldAlert,Tags,Wrench,Camera,Keyboard} from 'lucide-react'; import ImageUploader from './components/ImageUploader.jsx'; import RecognitionEditor from './components/RecognitionEditor.jsx'; import ResearchResult from './components/ResearchResult.jsx'; import TextSearch from './components/TextSearch.jsx'; import {useImageTools} from './hooks/useImageTools.js'; import {readVision,researchProduct,researchText} from './services/api.js';
const focuses=[['auto','Automatisch'],['device','Gerät'],['label','Etikett / Typenschild'],['display','Display / Fehlercode']];
const modes=[['identify','Identifizieren'],['troubleshoot','Fehler suchen'],['documents','Dokumente'],['replacement','Ersatzteil']];
export default function App(){const tools=useImageTools();const[source,setSource]=useState('text');const[query,setQuery]=useState('');const[textValues,setTextValues]=useState({query:'',manufacturer:'',model:''});const[focus,setFocus]=useState('auto');const[mode,setMode]=useState('identify');const[step,setStep]=useState('capture');const[vision,setVision]=useState(null);const[values,setValues]=useState({});const[research,setResearch]=useState(null);const[loading,setLoading]=useState(false);const[researching,setResearching]=useState(false);const[error,setError]=useState(null);
 const canRead=tools.images.length>0;
 async function read(){if(!canRead)return;setLoading(true);setError(null);try{const data=await readVision({images:tools.images,focus,query});setVision(data);setValues(data.identifiers||{});setStep('recognition');}catch(e){setError({message:e.message,code:e.code,details:e.details});}finally{setLoading(false)}}
 async function researchNow(){setResearching(true);setError(null);try{const data=await researchProduct({...values,query,rawText:vision?.rawText?.join('\n')||'',mode});setResearch(data);setStep('result');}catch(e){setError({message:e.message,code:e.code,details:e.details});}finally{setResearching(false)}}
 async function textSearch(){setLoading(true);setError(null);try{const data=await researchText({...textValues,query:textValues.query||textValues.model||textValues.manufacturer,mode});setResearch(data);setValues(data.normalized||textValues);setStep('result');}catch(e){setError({message:e.message,code:e.code,details:e.details});}finally{setLoading(false)}}
 function reset(){tools.clear();setQuery('');setTextValues({query:'',manufacturer:'',model:''});setFocus('auto');setMode('identify');setVision(null);setValues({});setResearch(null);setError(null);setStep('capture');window.scrollTo({top:0,behavior:'smooth'})}
 const status=useMemo(()=>step==='capture'?(source==='text'?'TYPSUCHE':'BILD ERFASSEN'):step==='recognition'?'DATEN PRÜFEN':'RECHERCHE FERTIG',[step,source]);
 return <><header><div className="brand"><div className="logo"><Wrench/></div><div><h1>ANDIS</h1><p>TECHNIKER-APP</p></div></div><div className="release-badge"><strong>V3.1</strong><small>STABILITY</small></div></header><main><section className="hero card"><div className="system-line"><Cpu/> TECHNISCHER ASSISTENT <b>{status}</b></div><div className="release-strip"><span>NEU</span><b>Stabilere Bildlesung mit automatischem Retry</b></div><h2>Erkennen. Prüfen. Recherchieren.</h2><p>Direkte Typensuche und Bildanalyse bleiben getrennt, nachvollziehbar und führen anschließend in dieselbe herstellerzentrierte Recherche.</p>{step==='capture'&&<div className="source-switch"><button className={source==='text'?'active':''} onClick={()=>setSource('text')}><Keyboard/> Typ eingeben</button><button className={source==='image'?'active':''} onClick={()=>setSource('image')}><Camera/> Foto analysieren</button></div>}<div className="pipeline"><span className={step==='capture'?'active':''}>1 Eingabe</span><span className={step==='recognition'?'active':''}>2 Daten prüfen</span><span className={step==='result'?'active':''}>3 Hersteller → Internet</span></div></section>
 {error&&<section className="error-card card"><ShieldAlert/><div><b>{error.code||'TECHNISCHER FEHLER'}</b><p>{error.message}</p>{error.details&&<details><summary>Details</summary><pre>{JSON.stringify(error.details,null,2)}</pre></details>}</div></section>}
 {step==='capture'&&source==='text'&&<TextSearch values={textValues} setValues={setTextValues} mode={mode} setMode={setMode} loading={loading} onSearch={textSearch}/>} 
 {step==='capture'&&source==='image'&&<section className="card"><div className="section-head"><div><span className="eyebrow">BILDANALYSE</span><h2>Foto oder Etikett lesen</h2></div><Tags/></div><label className="searchbox"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Optionale Hinweise, Hersteller oder Code"/></label><div className="choice-title">Analyseziel</div><div className="choices">{focuses.map(([k,l])=><button className={focus===k?'active':''} onClick={()=>setFocus(k)} key={k}>{l}</button>)}</div><div className="choice-title">Spätere Recherche</div><div className="choices">{modes.map(([k,l])=><button className={mode===k?'active':''} onClick={()=>setMode(k)} key={k}>{l}</button>)}</div><ImageUploader tools={tools} onCode={code=>{setQuery(code);setTextValues(v=>({...v,query:code}))}}/><button className="primary wide" disabled={!canRead||loading} onClick={read}><Gauge/>{loading?'Bild wird gelesen …':'Nur Bild lesen'}</button><p className="cost-note">Nach der Bildlesung kannst du erkannte Angaben prüfen. Erst danach startet die Hersteller- und Internetsuche.</p></section>}
 {step==='recognition'&&<RecognitionEditor vision={vision} values={values} setValues={setValues} researching={researching} onResearch={researchNow} onBack={()=>setStep('capture')}/>} 
 {step==='result'&&<ResearchResult research={research} recognition={values} onNew={reset}/>}<section className="safety card"><ShieldAlert/><div><b>Sicher arbeiten</b><p>KI-Angaben prüfen. Herstellerunterlagen und betriebliche Vorgaben haben Vorrang.</p></div></section></main></>}
