import {useMemo,useState} from 'react'; import {Cpu,Gauge,Search,ShieldAlert,Tags,Wrench} from 'lucide-react'; import ImageUploader from './components/ImageUploader.jsx'; import RecognitionEditor from './components/RecognitionEditor.jsx'; import ResearchResult from './components/ResearchResult.jsx'; import {useImageTools} from './hooks/useImageTools.js'; import {readVision,researchProduct} from './services/api.js';
const focuses=[['auto','Automatisch'],['device','Gerät'],['label','Etikett / Typenschild'],['display','Display / Fehlercode']];
const modes=[['identify','Identifizieren'],['troubleshoot','Fehler suchen'],['documents','Dokumente'],['replacement','Ersatzteil']];
export default function App(){const tools=useImageTools();const[query,setQuery]=useState('');const[focus,setFocus]=useState('auto');const[mode,setMode]=useState('identify');const[step,setStep]=useState('capture');const[vision,setVision]=useState(null);const[values,setValues]=useState({});const[research,setResearch]=useState(null);const[loading,setLoading]=useState(false);const[researching,setResearching]=useState(false);const[error,setError]=useState(null);
const canRead=tools.images.length>0;
async function read(){if(!canRead)return;setLoading(true);setError(null);try{const data=await readVision({images:tools.images,focus,query});setVision(data);setValues(data.identifiers||{});setStep('recognition');}catch(e){setError({message:e.message,code:e.code,details:e.details});}finally{setLoading(false)}}
async function researchNow(){setResearching(true);setError(null);try{const data=await researchProduct({...values,rawText:vision.rawText?.join('\n')||'',mode});setResearch(data);setStep('result');}catch(e){setError({message:e.message,code:e.code,details:e.details});}finally{setResearching(false)}}
function reset(){tools.clear();setQuery('');setFocus('auto');setMode('identify');setVision(null);setValues({});setResearch(null);setError(null);setStep('capture');window.scrollTo({top:0,behavior:'smooth'})}
const status=useMemo(()=>step==='capture'?'BILD ERFASSEN':step==='recognition'?'DATEN PRÜFEN':'RECHERCHE FERTIG',[step]);
return <><header><div className="brand"><div className="logo"><Wrench/></div><div><h1>ANDIS</h1><p>TECHNIKER-APP</p></div></div><span>V2.0</span></header><main><section className="hero card"><div className="system-line"><Cpu/> TECHNISCHER ASSISTENT <b>{status}</b></div><h2>Erkennen. Bestätigen. Recherchieren.</h2><p>Die Bilderkennung und die Internetrecherche laufen bewusst getrennt. So bleibt ein erkanntes Typenschild erhalten, selbst wenn die Recherche einmal ausfällt.</p><div className="pipeline"><span className={step==='capture'?'active':''}>1 Bild lesen</span><span className={step==='recognition'?'active':''}>2 Daten prüfen</span><span className={step==='result'?'active':''}>3 Recherchieren</span></div></section>
{error&&<section className="error-card card"><ShieldAlert/><div><b>{error.code||'TECHNISCHER FEHLER'}</b><p>{error.message}</p>{error.details&&<details><summary>Details</summary><pre>{JSON.stringify(error.details,null,2)}</pre></details>}</div></section>}
{step==='capture'&&<section className="card"><div className="section-head"><div><span className="eyebrow">SCHRITT 1 · ERFASSEN</span><h2>Foto oder Etikett lesen</h2></div><Tags/></div><label className="searchbox"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Optionale Hinweise, Hersteller oder Code"/></label><div className="choice-title">Analyseziel</div><div className="choices">{focuses.map(([k,l])=><button className={focus===k?'active':''} onClick={()=>setFocus(k)} key={k}>{l}</button>)}</div><div className="choice-title">Spätere Recherche</div><div className="choices">{modes.map(([k,l])=><button className={mode===k?'active':''} onClick={()=>setMode(k)} key={k}>{l}</button>)}</div><ImageUploader tools={tools} onCode={setQuery}/><button className="primary wide" disabled={!canRead||loading} onClick={read}><Gauge/>{loading?'Bild wird gelesen …':'Nur Bild lesen'}</button><p className="cost-note">Dieser Schritt nutzt keine Websuche. Erst nach deiner Bestätigung wird recherchiert.</p></section>}
{step==='recognition'&&<RecognitionEditor vision={vision} values={values} setValues={setValues} researching={researching} onResearch={researchNow} onBack={()=>setStep('capture')}/>} 
{step==='result'&&<ResearchResult research={research} recognition={values} onNew={reset}/>}<section className="safety card"><ShieldAlert/><div><b>Sicher arbeiten</b><p>KI-Angaben prüfen. Herstellerunterlagen und betriebliche Vorgaben haben Vorrang.</p></div></section></main></>}
