import { Router } from 'express';
import { z } from 'zod';
import { researchProduct, researchText } from '../services/research.js';
const router=Router();
const mode=z.enum(['identify','troubleshoot','documents','replacement']).optional().default('identify');
const productSchema=z.object({query:z.string().max(1000).optional().default(''),manufacturer:z.string().max(200).optional().default(''),productFamily:z.string().max(300).optional().default(''),partNumber:z.string().max(200).optional().default(''),model:z.string().max(300).optional().default(''),serialNumber:z.string().max(200).optional().default(''),errorCode:z.string().max(200).optional().default(''),rawText:z.string().max(5000).optional().default(''),mode});
const textSchema=z.object({query:z.string().trim().min(2,'Bitte mindestens zwei Zeichen eingeben.').max(1000),manufacturer:z.string().max(200).optional().default(''),productFamily:z.string().max(300).optional().default(''),partNumber:z.string().max(200).optional().default(''),model:z.string().max(300).optional().default(''),mode});
router.post('/product',async(req,res,next)=>{try{res.json(await researchProduct(productSchema.parse(req.body)));}catch(e){next(e);}});
router.post('/text',async(req,res,next)=>{try{res.json(await researchText(textSchema.parse(req.body)));}catch(e){next(e);}});
export default router;
