import {useEffect,useRef,useState} from 'react'; import {Check,X} from 'lucide-react';
export default function CropModal({src,onClose,onApply}){const canvasRef=useRef(null);const[start,setStart]=useState(null);const[rect,setRect]=useState(null);const[meta,setMeta]=useState(null);
useEffect(()=>{const img=new Image();img.onload=()=>{const c=canvasRef.current;const maxW=Math.min(window.innerWidth-48,700),maxH=Math.min(window.innerHeight*.58,650),s=Math.min(maxW/img.width,maxH/img.height);c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);setMeta({img,w:c.width,h:c.height});};img.src=src;},[src]);
function draw(r=rect){if(!meta)return;const c=canvasRef.current,x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.drawImage(meta.img,0,0,c.width,c.height);if(r){x.fillStyle='rgba(0,0,0,.48)';x.fillRect(0,0,c.width,c.height);x.clearRect(r.x,r.y,r.w,r.h);x.strokeStyle='#50ded2';x.lineWidth=3;x.strokeRect(r.x,r.y,r.w,r.h);}}
useEffect(()=>draw(),[rect,meta]);
function point(e){const b=canvasRef.current.getBoundingClientRect();const p=e.touches?.[0]||e;return{x:Math.max(0,Math.min(b.width,p.clientX-b.left)),y:Math.max(0,Math.min(b.height,p.clientY-b.top))};}
function down(e){e.preventDefault();const p=point(e);setStart(p);setRect({x:p.x,y:p.y,w:0,h:0});}
function move(e){if(!start)return;e.preventDefault();const p=point(e);setRect({x:Math.min(start.x,p.x),y:Math.min(start.y,p.y),w:Math.abs(p.x-start.x),h:Math.abs(p.y-start.y)});}
function up(){setStart(null)}
function apply(){if(!rect||rect.w<30||rect.h<30)return;const c=canvasRef.current,out=document.createElement('canvas');out.width=Math.round(rect.w);out.height=Math.round(rect.h);out.getContext('2d').drawImage(c,rect.x,rect.y,rect.w,rect.h,0,0,out.width,out.height);onApply(out.toDataURL('image/jpeg',.96));}
return <div className="modal"><div className="modal-card"><div className="modal-head"><div><strong>Etikett zuschneiden</strong><span>Ziehe einen Rahmen um den relevanten Bereich.</span></div><button onClick={onClose}><X/></button></div><canvas ref={canvasRef} onMouseDown={down} onMouseMove={move} onMouseUp={up} onMouseLeave={up} onTouchStart={down} onTouchMove={move} onTouchEnd={up}/><div className="modal-actions"><button className="ghost" onClick={onClose}>Abbrechen</button><button className="primary" disabled={!rect||rect.w<30||rect.h<30} onClick={apply}><Check/> Ausschnitt übernehmen</button></div></div></div>}
